# Knight’s Possible Moves
py = int(input())
px = int(input())
print(py + 1, px + 2)
print(py + 1, px - 2)
print(py - 1, px + 2)
print(py - 1, px - 2)
print(py + 2, px + 1)
print(py + 2, px - 1)
print(py - 2, px + 1)
print(py - 2, px - 1)
